version: "3.1"
services:

  mongo:
    container_name: sheep-mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=sheep
    ports:
      - "27017:27017"

